name: Test Production Build
on: [push]
jobs:
  run-the-project:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          yarn install
          yarn run build --if-present
          yarn start & npx wait-on http://localhost:3000
    env:
        CI: true

