name: Notify slack
on: 
  pull_request: 
    branches: [ main ]
env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
jobs: 
  slack-notifer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name:  send-message-to-slack
      
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"D01JUAQLVJR\",\"text\":\"Hello world\"}'