name: slack-notification
on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
jobs:
  slackNotification:
    name: slack-notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: slack-notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME : ${{ secrets.SLACK_USERNAME }}
        SLACK_MSG_AUTHOR: $GITHUB_ACTOR
        SLACK_ICON : https://mwblive-0obrejwqde.netdna-ssl.com/wp-content/uploads/2018/12/mwb-logo.png
        SLACK_COLOR: '#643eff'
        
