name: slack-notification
on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
env:
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
jobs:
  slackNotification:
    name: slack-notification
    runs-on: ubuntu-latest
    steps:
    - uses: rtCamp/action-slack-notify@v2
      run: echo  ${{ COMMIT_MESSAGE }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME : ${{ secrets.SLACK_USERNAME }}
        SLACK_ICON : https://mwblive-0obrejwqde.netdna-ssl.com/wp-content/uploads/2018/12/mwb-logo.png
        SLACK_COLOR: '#643eff'
        SLACK_MESSAGE: ${{ COMMIT_MESSAGE }}


